workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Сборка APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
