workflows:
  cordova-android:
    name: Cordova Android App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 11
      xcode: 16.2
      android_signing:
        - keystore_reference
      groups:
        - cordova
      vars:
        CORDOVA_VERSION: 12.0.0
    scripts:
      - name: Проверка версии Node и NPM
        script: |
          node --version
          npm --version
      - name: Проверка Android SDK
        script: |
          echo $ANDROID_SDK_ROOT
          ls -la $ANDROID_SDK_ROOT/platform-tools || true
          ls -la $ANDROID_SDK_ROOT/build-tools || true
      - name: Установка Cordova
        script: |
          npm install -g cordova@$CORDOVA_VERSION
          cordova -v
      - name: Установка зависимостей проекта
        script: |
          npm install
      - name: Добавление Android платформы
        script: |
          cordova platform rm android || true
          cordova platform add android
      - name: Сборка APK
        script: |
          cordova build android --release --verbose
    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
