workflows:
  cordova-android:
    name: Cordova Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.x
      npm: latest
      java: 11
    scripts:
      - name: Установка зависимостей
        script: |
          npm install -g cordova
          npm install
      - name: Добавление Android платформы
        script: |
          cordova platform add android || true
      - name: Проверка зависимостей
        script: |
          cordova requirements
      - name: Сборка APK
        script: |
          cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
